version: '3'
services:
  db:
    image: postgres:12.9
    container_name: survey-pf-db
    environment:
      - POSTGRES_USER=survey_admin
      - POSTGRES_PASSWORD=survey_admin
      - POSTGRES_DB=survey_db
    ports:
      - '15432:5432'
  pgweb:
    image: sosedoff/pgweb
    environment:
      - DATABASE_URL=postgres://survey_admin:survey_admin@db:5432/survey_db?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      - db

  survey:
    container_name: survey-pf-v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
